const products=[
 {id:1,name:'The Sol',category:'sneakers',price:145,color:'Bone',image:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=85',tag:'Bestseller'},
 {id:2,name:'The Miro',category:'loafers',price:180,color:'Espresso',image:'https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=700&q=85',tag:''},
 {id:3,name:'The Noma',category:'boots',price:220,color:'Onyx',image:'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=700&q=85',tag:'New'},
 {id:4,name:'The Alma',category:'sandals',price:125,color:'Caramel',image:'https://images.unsplash.com/photo-1562273138-f46be4ebdf33?auto=format&fit=crop&w=700&q=85',tag:''},
 {id:5,name:'The Dune',category:'sneakers',price:155,color:'Clay',image:'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=700&q=85',tag:''},
 {id:6,name:'The Cielo',category:'loafers',price:195,color:'Moss',image:'https://images.unsplash.com/photo-1614252369475-531eba835eb1?auto=format&fit=crop&w=700&q=85',tag:''},
 {id:7,name:'The Vale',category:'boots',price:240,color:'Chestnut',image:'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=700&q=85',tag:''},
 {id:8,name:'The Lune',category:'sandals',price:135,color:'Ivory',image:'https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&w=700&q=85',tag:''}
];
let cart=JSON.parse(localStorage.getItem('aure-cart')||'[]');
const $=s=>document.querySelector(s); const money=n=>`$${n.toFixed(2)}`;
function renderProducts(filter='all'){const list=filter==='all'?products:products.filter(p=>p.category===filter);$('#productGrid').innerHTML=list.map(p=>`<article class="product-card"><div class="product-image">${p.tag?`<span class="badge">${p.tag}</span>`:''}<img src="${p.image}" alt="${p.name} ${p.color} footwear" loading="lazy"><button class="quick-add" onclick="addToCart(${p.id})">Add to bag <span>+</span></button></div><div class="product-info"><div><p>${p.name}</p><small>${p.color} / ${p.category}</small></div><strong>${money(p.price)}</strong></div></article>`).join('')}
function addToCart(id){const item=cart.find(x=>x.id===id);item?item.qty++:cart.push({id,qty:1});saveCart();openBag()}
function saveCart(){localStorage.setItem('aure-cart',JSON.stringify(cart));renderCart()}
function renderCart(){let count=cart.reduce((s,x)=>s+x.qty,0);$('#bagCount').textContent=count;$('#drawerCount').textContent=`(${count})`;let total=0;$('#cartItems').innerHTML=cart.length?cart.map(item=>{const p=products.find(x=>x.id===item.id);total+=p.price*item.qty;return `<div class="cart-row"><img src="${p.image}" alt="${p.name}"><div><h3>${p.name}</h3><p>${p.color} · ${money(p.price)} · Qty ${item.qty}</p><button class="remove" onclick="removeFromCart(${p.id})">Remove</button></div></div>`}).join(''):'<p class="empty">Your bag is waiting for something special.</p>';$('#subtotal').textContent=money(total)}
function removeFromCart(id){cart=cart.filter(x=>x.id!==id);saveCart()};function openBag(){$('#cartDrawer').classList.add('open');$('#overlay').classList.add('show')};function closeBag(){$('#cartDrawer').classList.remove('open');$('#overlay').classList.remove('show')}
$('.controls').addEventListener('click',e=>{if(e.target.matches('.filter')){$$('.filter').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');renderProducts(e.target.dataset.filter)}});function $$(s){return document.querySelectorAll(s)}
$('#bagBtn').onclick=openBag;$('#closeBag').onclick=closeBag;$('#overlay').onclick=closeBag;$('#searchBtn').onclick=()=>{$('#searchModal').classList.add('open');$('#overlay').classList.add('show');$('#searchInput').focus()};$('#closeSearch').onclick=()=>{$('#searchModal').classList.remove('open');$('#overlay').classList.remove('show')};$('#searchInput').oninput=e=>{const q=e.target.value.toLowerCase();$('#searchResults').innerHTML=products.filter(p=>(p.name+' '+p.color+' '+p.category).toLowerCase().includes(q)).map(p=>`<div class="search-result">${p.name} <span>${money(p.price)}</span></div>`).join('')};$('#newsletterForm').onsubmit=e=>{e.preventDefault();$('#formMessage').textContent='You’re on the list — welcome to Auré.';e.target.reset()};$('#checkoutBtn').onclick=()=>cart.length?alert('Checkout is ready to connect to Stripe or your preferred payment provider. Your cart is saved.'):alert('Your bag is empty.');renderProducts();renderCart();
